### ISSUE TITLE
Support for Python3.8 with Amazon Linux 2

### ISSUE THREAD

**Issue by sujee81** [myrmex-org/docker-lambda-packager#11]
Thanks for creating and sharing this tool. It is useful for my python lambda packaging. Lambda recently added support for Python 3.8 which runs on Amazon Linux 2. It would be great if you could help to add that support in docker-lambda-packager.
Thanks again.

Cheers
Sujeevan

**Comment by AlexisNo** [comment]
Hi @sujee81,
Sorry for the very late reply 😓 
Support for Python 3.8 is available with the new usage of docker-lambda-packager. Now the packager creates the zip archive and we don't need a workaround for permissions. I will continue to think how it can be improved. Feedback is welcome !

**Comment by sujee81** [comment]
That is awesome. I will test next time I try to package my lambda and share the results here. Thanks again for your work.
