### ISSUE TITLE
AmazonLinux version mismatch with AWS Lambda

### ISSUE THREAD

**Issue by acurus-puppetmaster** [myrmex-org/docker-lambda-packager#4]
This image is built upon amazonlinux:latest which is now amazonlinux:2 but AWS Lambda is still amazonlinux:1 [AWS Lambda supported versions](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html)

This really should be tied back to amazonlinux:1 otherwise binary python packages may not get the correct runtimes.

**Comment by acurus-puppetmaster** [comment]
Just forked the code and ran with amazonlinux:1 and it fixed my issue with pyarrow and numpy, numpy wasn't being loaded because I believe numpy's binary libraries that get built weren't compatible with AWS Lambda under amazonlinux:2

**Comment by acurus-puppetmaster** [comment]
Aug 28, 2018 is the date when aws/amazon-linux-docker-images switched to amazonlinux:2 it seems.

**Comment by AlexisNo** [comment]
Thanks a lot for the feedback :pray:, I fixed the version in the Dockerfile.
